class Student:
    def __init__(self, id, name, courses):
        self.id = id
        self.name = name
        self. courses = courses

    def register_courses(self):
        if course not in self.courses:
            self.courses.append(course)
            print(f"{course} has been registered)
        else:
             print(f"{course} )          
                     
    def unregister_courses(self):








    #Register        
        